In [1]:
from numpy import asarray
from keras.models import Sequential
from keras.layers import UpSampling2D
X = asarray([[1, 2],[3, 4]])
print(X)

[[1 2]
 [3 4]]


In [2]:
X = X.reshape((1,2,2,1))

In [3]:
model = Sequential()
model.add(UpSampling2D(input_shape=(2,2,1)))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d (UpSampling2D) (None, 4, 4, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [4]:
yhat = model.predict(X)

In [5]:
yhat = yhat.reshape((4,4))
print(yhat)

[[1. 1. 2. 2.]
 [1. 1. 2. 2.]
 [3. 3. 4. 4.]
 [3. 3. 4. 4.]]


In [6]:
X = asarray([[1, 2],[3, 4]])
print(X)
X = X.reshape((1,2,2,1))
model_one = Sequential()
model_one.add(UpSampling2D(input_shape=(2,2,1),size=(2,3)))
model_one.summary()
yhat = model_one.predict(X)
print(yhat)

[[1 2]
 [3 4]]
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_1 (UpSampling2 (None, 4, 6, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
[[[[1.]
   [1.]
   [1.]
   [2.]
   [2.]
   [2.]]

  [[1.]
   [1.]
   [1.]
   [2.]
   [2.]
   [2.]]

  [[3.]
   [3.]
   [3.]
   [4.]
   [4.]
   [4.]]

  [[3.]
   [3.]
   [3.]
   [4.]
   [4.]
   [4.]]]]


In [7]:
X = asarray([[1, 2],[3, 4]])
print(X)
X = X.reshape((1,2,2,1))
model_two = Sequential()
model_two.add(UpSampling2D(input_shape=(2,2,1),interpolation='bilinear'))
model_two.summary()
yhat = model_two.predict(X)
yhat = yhat.reshape((4,4))
print(yhat)

[[1 2]
 [3 4]]
Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_2 (UpSampling2 (None, 4, 4, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
[[1.   1.25 1.75 2.  ]
 [1.5  1.75 2.25 2.5 ]
 [2.5  2.75 3.25 3.5 ]
 [3.   3.25 3.75 4.  ]]


In [8]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Reshape
from keras.layers import UpSampling2D
from keras.layers import Conv2D
model_three = Sequential()
model_three.add(Dense(128*5*5, input_dim=100))
model_three.add(Reshape((5,5,128)))

In [9]:
model_three.add(UpSampling2D())

In [10]:
model_three.add(Conv2D(1,(3,3), padding='same'))
model_three.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 3200)              323200    
_________________________________________________________________
reshape (Reshape)            (None, 5, 5, 128)         0         
_________________________________________________________________
up_sampling2d_3 (UpSampling2 (None, 10, 10, 128)       0         
_________________________________________________________________
conv2d (Conv2D)              (None, 10, 10, 1)         1153      
Total params: 324,353
Trainable params: 324,353
Non-trainable params: 0
_________________________________________________________________


In [11]:
from numpy import asarray
from keras.models import Sequential
from keras.layers import Conv2DTranspose
X = asarray([[1, 2],[3, 4]])
print(X)

[[1 2]
 [3 4]]


In [12]:
X = X.reshape((1,2,2,1))

In [13]:
model_four = Sequential()
model_four.add(Conv2DTranspose(1,(1,1), strides=(2,2), input_shape=(2,2,1)))
model_four.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_transpose (Conv2DTran (None, 4, 4, 1)           2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [14]:
weights = [asarray([[[[1]]]]), asarray([0])]
model_four.set_weights(weights)

In [15]:
yhat = model_four.predict(X)

In [16]:
yhat = yhat.reshape((4, 4))
print(yhat)

[[1. 0. 2. 0.]
 [0. 0. 0. 0.]
 [3. 0. 4. 0.]
 [0. 0. 0. 0.]]


In [18]:
X = asarray([[1, 2],[3, 4]])
print(X)
X = X.reshape((1,2,2,1))
model_five = Sequential()
model_five.add(Conv2DTranspose(1,(3,3), strides=(2,2), padding='same', input_shape=(2,2,1)))
model_five.summary()
yhat = model_five.predict(X)
yhat = yhat.reshape((4, 4))
print(yhat)

[[1 2]
 [3 4]]
Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_transpose_2 (Conv2DTr (None, 4, 4, 1)           10        
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________
[[-0.10254961  0.40305585 -0.70560926  0.8061117 ]
 [-0.4372928  -0.45387715 -0.57637924 -0.9077543 ]
 [-0.77183604  0.6760025  -2.783958    0.54589343]
 [-1.3118784  -1.3616314  -0.8545521  -1.8155086 ]]


In [19]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Reshape
from keras.layers import Conv2DTranspose
from keras.layers import Conv2D
model_six = Sequential()
model_six.add(Dense(128*5*5, input_dim=100))

In [20]:
model_six.add(Reshape((5,5,128)))
model_six.add(Conv2DTranspose(1,(3,3), strides=(2,2), padding='same'))
model_six.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 3200)              323200    
_________________________________________________________________
reshape_1 (Reshape)          (None, 5, 5, 128)         0         
_________________________________________________________________
conv2d_transpose_3 (Conv2DTr (None, 10, 10, 1)         1153      
Total params: 324,353
Trainable params: 324,353
Non-trainable params: 0
_________________________________________________________________
